// Generated by https://quicktype.io

import { Album } from "./Album";

export interface AlbumsResponse {
  albums: Album[];
}

export interface ExternalUrls {
  spotify: string;
}

export interface Copyright {
  text: string;
  type: string;
}

export interface ExternalIDS {
  upc: string;
}



interface Vector { x: number; y: number, length: number }
interface Point { x: number; y: number }

let v: Vector = { x: 23, y: 34, length: 123 }
let p: Point = { x: 23, y: 34 }

// v = p // Property 'length' is missing in type 'Point' but required in type 'Vector' 
p = v  // OK

