// Generated by https://quicktype.io

import { Album } from "./Album";

export interface AlbumsResponse {
  albums: Album[];
}

export interface ExternalUrls {
  spotify: string;
}

export interface Copyright {
  text: string;
  type: string;
}

export interface ExternalIDS {
  upc: string;
}


